<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Metodo Get</title>
</head>
<body>


<form action="./resultadoPOST.PHP" method="POST">

Nombre: 
<input type="text" name="nombre">
<br><br>
Correo:
<input type="email" name="correo">
<br><br>
Edad:
<input type="number" name="edad" >
<br/><br>
Password:
<input type="password" name="password" >
<br><br>

<button type="submit">Enviar Datos</button>

    </form>
</body>
</html>